# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rack-forceie7}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Andrew Chalkley"]
  s.date = %q{2010-01-31}
  s.description = %q{Rack::ForceIE7 adds the X-UA-Compatible header with the value of IE=7 to the response headers so that there is no need to include anything in the head of your HTML document. Unlike some other middleware this doesn't edit your body - it just adds the additional header to the response.}
  s.email = %q{andrew@chalkley.org}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/rack-forceie7.rb",
     "rack-forceie7.gemspec",
     "test/helper.rb",
     "test/test_rack-forceie7.rb"
  ]
  s.homepage = %q{http://github.com/chalkers/rack-forceie7}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Rack middleware to force Internet Explorer 8 to render pages in Internet Explorer 7 Compatibilty mode unobtrusively}
  s.test_files = [
    "test/helper.rb",
     "test/test_rack-forceie7.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
  end
end

